### ISSUE TITLE
ImportError: No module named rospy_message_converter.message_converter

### ISSUE THREAD

**Issue by parisChatz** [eurogroep/rosbag_pandas#5]
Installed this lib from source (pip install git+https://github.com/eurogroep/rosbag_pandas.git).
I'm working on a virtual env with python 2.7 and when I'm importing rosbag_pandas I get the following error.

```
Traceback (most recent call last):
  File "rosbag_data_extraction.py", line 9, in <module>
    import rosbag_pandas
  File "/home/parischatz/entropy_ws/src/hrt_entropy/data_viz/venv/lib/python2.7/site-packages/rosbag_pandas/__init__.py", line 1, in <module>
    from .rosbag_pandas import RosbagPandaException, bag_to_dataframe, topics_from_keys
  File "/home/parischatz/entropy_ws/src/hrt_entropy/data_viz/venv/lib/python2.7/site-packages/rosbag_pandas/rosbag_pandas.py", line 9, in <module>
    from rospy_message_converter.message_converter import convert_ros_message_to_dictionary
ImportError: No module named rospy_message_converter.message_converter
```

**Comment by reinzor** [comment]
Hi, this is a ROS package, please install using the ROS debians or from a workspace
